### ISSUE TITLE
How to restart or stop nginx?

### ISSUE THREAD

**Issue by educate** [jogolor/openshift-cartridge-nginx#1]
Hi,
How to restart or stop nginx? Root directive is /public, I create a html file inside, why does it still show me default openshift welcome page?

Best regards,
Ethan

**Comment by educate** [comment]
Sorrry, I didn't notice there was a index.html file in public. Just tell me how start/stop/restart ngiinx? I want to use command line like `service nginx restart` for convenience. Thank you!

**Comment by jogolor** [comment]
SSH into you application. 
To stop nginx, use:  ${OPENSHIFT_NGINX_DIR}/bin/control stop
To start nginx, use:  ${OPENSHIFT_NGINX_DIR}/bin/control start

You can find the others in the file ${OPENSHIFT_NGINX_DIR}/bin/control
