### ISSUE TITLE
How to install GD Library with PHP 7?

### ISSUE THREAD

**Issue by educate** [jogolor/openshift-cartridge-nginx#2]
Hi,
A warning presented itself:
_The requested PHP extension ext-gd * is missing from your system. Install or enable PHP's gd extension._

In fact, the GD Library is in the system, it can not be used by php though
run
`rpm -qa | grep gd`
found this package
**gd-2.0.35-26.el7.x86_64**
continued to run
`rpm -ql gd-2.0.35-26.el7.x86_64`
came the results:
**/usr/lib64/libgd.so.2
/usr/lib64/libgd.so.2.0.0
/usr/share/doc/gd-2.0.35
/usr/share/doc/gd-2.0.35/COPYING
/usr/share/doc/gd-2.0.35/NEWS
/usr/share/doc/gd-2.0.35/README-JPEG.TXT
/usr/share/doc/gd-2.0.35/index.html**

I didn't know that, then I installed the "missing GD" by running
`sudo yum install php-gd* `

I thought libgd.so.2 and the other 6 files were generated after the above command, in fact, they were there when nginx was installed. My PHP extension dir is /usr/lib64/php/modules, I copied libgd.so.2.0.0 to that directive, changed its name to libgd.so, created a new file libgd.ini in order to enable the extension. 
But when I checked php extensions by running php -m , I got the warning msg "PHP Warning:  PHP Startup: Invalid library (maybe not a PHP library) 'libgd.so' in Unknown on line 0",

Later I noticed php70w-gd was available in webtatic's repository, and it worked with php7 with problem. You know, I mistook libgd.so.2 was the result of running `sudo yum install php-gd* `, so I began to remove it, but execution aborted due to dependence, it was needed by nginx, nonetheless, I continuted to remove it by adding --nodeps in the command.

When I tried to restart nginx, end in failure for the reason that:
Sep 27 23:00:44 ip-172-31-32-13.us-west-2.compute.internal nginx[9116]: nginx: [emerg] dlopen() "/usr/lib64/nginx/modules/ngx_http_image_filter_module.so" failed (libgd.so.2: cannot open shared object file: No such file or directory) in /usr/share/nginx/modules/mod-http-image-filter.conf:1

Given that libgd.so.2 has been removed, I decide to install it manually
[ec2-user@ip-172-31-32-13 php7]$ sudo rpm -ivh gd-2.0.35-26.el7.i686.rpm
warning: gd-2.0.35-26.el7.i686.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY
error: Failed dependencies:
        libX11.so.6 is needed by gd-2.0.35-26.el7.i686
        libXpm.so.4 is needed by gd-2.0.35-26.el7.i686
        libc.so.6 is needed by gd-2.0.35-26.el7.i686
        libc.so.6(GLIBC_2.0) is needed by gd-2.0.35-26.el7.i686
        libc.so.6(GLIBC_2.1) is needed by gd-2.0.35-26.el7.i686
        libc.so.6(GLIBC_2.1.3) is needed by gd-2.0.35-26.el7.i686
        libc.so.6(GLIBC_2.11) is needed by gd-2.0.35-26.el7.i686
        libc.so.6(GLIBC_2.3.4) is needed by gd-2.0.35-26.el7.i686
        libc.so.6(GLIBC_2.4) is needed by gd-2.0.35-26.el7.i686
        libc.so.6(GLIBC_2.7) is needed by gd-2.0.35-26.el7.i686
        libfontconfig.so.1 is needed by gd-2.0.35-26.el7.i686
        libfreetype.so.6 is needed by gd-2.0.35-26.el7.i686
        libjpeg.so.62 is needed by gd-2.0.35-26.el7.i686
        libjpeg.so.62(LIBJPEG_6.2) is needed by gd-2.0.35-26.el7.i686
        libm.so.6 is needed by gd-2.0.35-26.el7.i686
        libm.so.6(GLIBC_2.0) is needed by gd-2.0.35-26.el7.i686
        libm.so.6(GLIBC_2.1) is needed by gd-2.0.35-26.el7.i686
        libpng15.so.15 is needed by gd-2.0.35-26.el7.i686
        libpng15.so.15(PNG15_0) is needed by gd-2.0.35-26.el7.i686
        libz.so.1 is needed by gd-2.0.35-26.el7.i686
[ec2-user@ip-172-31-32-13 php7]$
 
Holy shit, I prefer to reload the system and install nginx and php again.

**Comment by jogolor** [comment]
Recompile php 7 with GD support with optional "--with-gd=DIR". DIR is the GD library base                       install directory BUNDLED

OR

Use PHP 7's 'phpize' to install GD extension.  Google 'phpize gd', you can get it.

**Comment by jogolor** [comment]
I'm sorry I have no experience on it.
This may be a hint: http://idroot.net/tutorials/how-to-install-php-7-on-centos-7/
OR try PHP7's 'phpize'.
Google may be more helpful.

**Comment by educate** [comment]
Hi, 
Thank you for your reply. I installed php7 from webtatic's repository, GD extension is available in the same repo, I just missed it before.
Now I got another problem, I had installed a generic GD2, after installation, it generated libgd.so.2 and libgd.so.2.0.0 and four docs under /usr/lib64.
I began to uninstall them after i noticed php70w-gd was out there, when I was trying to remove libgd.so.2, execution blocked due to dependence,it was needed by nginx, but I continuted to remove it by adding --nodeps in the command.
 
Can of worms, when I try to restart nginx, end in failure,

_Sep 27 23:00:44 ip-172-31-32-13.us-west-2.compute.internal systemd[1]: Starting The nginx HTTP and reverse proxy server...
Sep 27 23:00:44 ip-172-31-32-13.us-west-2.compute.internal nginx[9116]: nginx: [emerg] dlopen() "/usr/lib64/nginx/modules/ngx_http_image_filter_module.so" failed (libgd.so.2: cannot open shared object file: No such file or directory) in /usr/share/nginx/modules/mod-http-image-filter.conf:1
Sep 27 23:00:44 ip-172-31-32-13.us-west-2.compute.internal nginx[9116]: nginx: configuration file /etc/nginx/nginx.conf test failed
Sep 27 23:00:44 ip-172-31-32-13.us-west-2.compute.internal systemd[1]: nginx.service: control process exited, code=exited status=1
Sep 27 23:00:44 ip-172-31-32-13.us-west-2.compute.internal systemd[1]: Failed to start The nginx HTTP and reverse proxy server.
Sep 27 23:00:44 ip-172-31-32-13.us-west-2.compute.internal systemd[1]: Unit nginx.service entered failed state.
Sep 27 23:00:44 ip-172-31-32-13.us-west-2.compute.internal systemd[1]: nginx.service failed._

I refer to google, but find no help, do you know how to fix the problem? Thank you!

**Comment by jogolor** [comment]
Here is the hint: libgd.so.2: cannot open shared object file: No such file or directory. 
The shared file 'libgd.so.2' was removed. I think you should install GD once again.

**Comment by educate** [comment]
Thanks for your advice. I find it hard to install this package again, i'll try another way to fix the problem.
